language: python
cache:
- pip
sudo: false
branches:
  only:
  - src
python:
- 3.6
before_install:
- openssl aes-256-cbc -K $encrypted_e865738ed3e8_key -iv $encrypted_e865738ed3e8_iv
  -in id_rsa.enc -out id_rsa -d
- git config --global user.name 'ylx2002'
- git config --global user.email 'ylxredbag@qq.com'
- git config --global push.default 'simple'
- echo -e 'Host github.com\n    StrictHostKeyChecking no' >> ~/.ssh/config
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa
- ssh-add id_rsa
- git remote rm origin
- git remote add origin git@github.com:ylx2002/ylx2002.github.io.git
- git fetch origin master
- git branch master FETCH_HEAD
install:
- pip install 'Nikola[extras]'
script:
- nikola build && nikola github_deploy -m 'Nikola auto deploy [ci skip]'
notifications:
  email:
    on_success: change
    on_failure: always
